version: '2.0'
services:
  database:
    image: "mysql:8.0"
    networks:
      - tb_network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: travel_bill_test

  api:
    build: .
    networks:
      - tb_network
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/travel_bill_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_password: example

networks:
  tb_network:
    driver: bridge
